## Import libraries

In [35]:
import numpy as np
import matplotlib.pyplot as plt
import cv2
from numpy import zeros, newaxis

## Loading Image

In [36]:
img = cv2.imread('number.jpg')
b, g, r = cv2.split(img)
thresholded = (g > np.mean(g))*g

In [37]:
indices = np.where(thresholded == [0])
#return as (y,x)
points = np.zeros(len(indices[0]))
points = points+indices
points = points.astype(int)
points = points.transpose()

In [38]:
y = points[:,0]
x = points[:,1]
y = y.astype(np.int16)
x = x.astype(np.int16)

## Initialzing histogram

In [40]:
H = 2
W = 2
lh = 3
lw = 3
hist = np.linspace(0,H*W, num = H*W, endpoint = False)
hist = hist.reshape((H,W))
hist = hist.astype(np.int16)
np.shape(hist)

(2, 2)

# Duplicate matrix on 1st axis

In [41]:
def duplicate_2dtensor(_2dtensor, number_duplicate):
    _3dtensor = _2dtensor[newaxis, :, :]
    _3dtensor = np.repeat(_3dtensor, number_duplicate, axis = 0)
    return _3dtensor

# Create 3d tensor from 1d tensor

In [42]:
def duplicate_1dtensor(_1dtensor, num_2nd_axis, num_3rd_axis):
    #duplicating on 2nd axis
    _2dtensor = _1dtensor[:, newaxis]
    _2dtensor = np.repeat(_2dtensor, num_2nd_axis, axis = 1)
    #duplicating on 3rd axis
    _3dtensor = _2dtensor[:,:,newaxis]
    _3dtensor = np.repeat(_3dtensor, num_3rd_axis, axis = 2)
    return _3dtensor

In [55]:
X = duplicate_1dtensor(x,H,W)
Y = duplicate_1dtensor(y,H,W)
print(X[1,:,:])

[[1 1]
 [1 1]]


## Check above
### a1 parameter 

In [44]:
a1 = lh*(hist%W) + lh
#create 3d matrix of a1
a1 = duplicate_2dtensor(a1, len(points))

In [51]:
a1[2,:,:]

array([[3, 6],
       [3, 6]], dtype=int16)

### b1 parameter

In [46]:
b1 = lw*(hist//W) + lw
#create 3d matrix of a1
b1 = duplicate_2dtensor(b1, len(points))

In [52]:
b1[2,:,:]

array([[3, 3],
       [6, 6]], dtype=int16)

In [60]:
above = b1+np.multiply(X,a1)-Y

In [61]:
print(b1[100,:,:])

[[3 3]
 [6 6]]


In [62]:
print(X[100,:,:])

[[166 166]
 [166 166]]


In [63]:
print(a1[100,:,:])

[[3 6]
 [3 6]]


In [65]:
print(Y[100,:,:])

[[0 0]
 [0 0]]


# Check below
### a0 parameter

In [77]:
a0 = lh*(hist%W)
#create 3d matrix of a0
a0 = duplicate_2dtensor(a0, len(points))
np.shape(a0)

(15835, 100, 100)

### b0 parameter

In [78]:
b0 = lw*(hist//W)
#create 3d matrix of b1
b0 = duplicate_2dtensor(b0, len(points))
np.shape(a0)

(15835, 100, 100)

In [96]:
k = np.array(([1,2,3,4]))
k1 = np.array(([5,6,7,8]))
np.multiply(k,k1)

array([ 5, 12, 21, 32])